name: clean-data
run-name: ${{ github.actor }} is cleaning the data and pushing to S3!
on: workflow_dispatch 
jobs:
  # This job will install required libs, clean the data, and stage cleaned data to an S3 Bucket
  clean-and-upload:
    env: 
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    runs-on: ubuntu-latest
    steps:
      # Checkout our repo
      - uses: actions/checkout@v3
      
      # Installing Python v3.10 and AWS CLI v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - uses: unfor19/install-aws-cli-action@v1
      
      - run: ls -a
      
      # install pandas
      - run: pip install pandas
      - run: python clean_script.py
      
      - run: aws s3 cp cleaned_data.csv s3://staged-for-training
    
    
  
