name: clean-data
run-name: ${{ github.actor }} is cleaning the data and pushing to S3!
on: workflow_dispatch 
jobs:
  # This job will install required libs, clean the data, and stage cleaned data to an S3 Bucket
  clean-data:
    runs-on: ubuntu-latest
    steps:
      # Installing Python v3.10 and AWS CLI v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - uses: unfor19/install-aws-cli-action@v1
      
      - run: echo $CLEANED_DATA_PATH
      - run: echo $DATA_BUCKET_POSTFIX
      - run: python clean_script.py
    
    
  
